### ISSUE TITLE
Questions about running the cola dataset script

### ISSUE THREAD

**Issue by dengxingzhi** [microsoft/LoRA#176]
hello,An error occurs when I run the debert cola.sh script
Traceback (most recent call last):
  File "examples/text-classification/run_glue.py", line 626, in <module>
    main()
  File "examples/text-classification/run_glue.py", line 558, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/dengxingzhi/LoRA/examples/NLU/src/transformers/trainer.py", line 881, in train
    self._load_state_dict_in_model(state_dict)
  File "/home/dengxingzhi/LoRA/examples/NLU/src/transformers/trainer.py", line 1987, in _load_state_dict_in_model
    if set(load_result.missing_keys) == set(self.model._keys_to_ignore_on_save):
TypeError: 'NoneType' object is not iterable

so,Is it a code problem,because running other scripts works fine

**Comment by Zhoutong-Wu** [comment]
I met the same problem, and I added the following in the _load_state_dict_in_model() function in transformers/trainer.py 
if self.model._keys_to_ignore_on_save == None:
            self.model._keys_to_ignore_on_save = []
Then I could run the cola.sh script.
