### ISSUE TITLE
NLU experiments error

### ISSUE THREAD

**Issue by jie040109** [microsoft/LoRA#180]
Traceback (most recent call last):
  File "examples/text-classification/run_glue.py", line 628, in <module>
    main()
  File "examples/text-classification/run_glue.py", line 360, in main
    masking_prob=model_args.masking_prob,
  File "/home/jjwang/workspace/LoRA/examples/NLU/src/transformers/models/auto/configuration_auto.py", line 388, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jjwang/workspace/LoRA/examples/NLU/src/transformers/configuration_utils.py", line 438, in get_config_dict
    use_auth_token=use_auth_token,
  File "/home/jjwang/workspace/LoRA/examples/NLU/src/transformers/file_utils.py", line 1142, in cached_path
    local_files_only=local_files_only,
  File "/home/jjwang/workspace/LoRA/examples/NLU/src/transformers/file_utils.py", line 1349, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by jie040109** [comment]
already solved, network error
