### ISSUE TITLE
Bug after the latest commit #63 

### ISSUE THREAD

**Issue by JizeZhangCS** [microsoft/LoRA#87]
## Phenomenon
layers.py, line 269, 
``` Traceback (most recent call last)
  File "/storage_fast/jzzhang/loralib/layers.py", line 308, in __init__
    super(Conv2d, self).__init__(nn.Conv2d, *args, **kwargs)
  File "/storage_fast/jzzhang/loralib/layers.py", line 269, in __init__
    self.conv.weight.new_zeros((out_channels//self.groups*kernel_size, r*kernel_size))
  File "/storage/jzzhang/miniconda3/envs/lora/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'groups'
```

## Analysis
In the latest commit, the change in line 257 make lora.Conv2d has no more inheritance from nn.Conv2d, but instead nn.Modules, which havn't a attribute called groups.

## Possible Solution
change line 269 to 
```self.conv.weight.new_zeros((out_channels//self.conv.groups*kernel_size, r*kernel_size))```

**Comment by edwardjhu** [comment]
Thanks! I fixed it.
